sentry prefect 2 blog post
coveo/source.coveo.com pull request #264
Opened 2023-01-04 21:39 UTC by jmprovencher

2023-01-04 21:54 UTC, pboucherCoveo requested changes
Suggestions provided. Nice work! This is awesome

2023-01-04 21:54 UTC, pboucherCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +In my last [blog post](https://source.coveo.com/2022/04/20/integrating-sentry-with-prefect-flows/), I described a practical way of integrating Sentry with Prefect 1 flows. Since then, [Prefect 2](htt
```suggestion
In my last [blog post](https://source.coveo.com/2022/04/20/integrating-sentry-with-prefect-flows/), I described a practical way of integrating Sentry with Prefect 1 flows. Since then, [Prefect 2](https://docs.prefect.io/) was released, and with it, many interesting capabilities were introduced. I won't spend time explaining why you should migrate to Prefect 2, but I suggest you have a look at the new features presented [here](https://docs.prefect.io/migration-guide/). If you're interested, I also created a step by step GitHub [repository](https://github.com/jmprovencher/prefect-tutorial) showcasing some of the new features available so that you can try it yourself.
```

2023-01-04 21:54 UTC, pboucherCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concept offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefect Clou
```suggestion
One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefect Cloud comes built-in with a collection of existing block types, but it also offers the possibility to define new one's. With that, it's possible to create reusable utilities that can be shared among flows and teams. This blog post will provide a step by step plan as to how to create a custom Sentry block type that will automatically send notifications to Slack in case of a flow failure.
```

2023-01-04 21:54 UTC, pboucherCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +Sentry is an error monitoring tool that enables developer teams to be notified rapidly when issues happen in their
```suggestion
Sentry is an error monitoring tool that enables developer teams to be notified rapidly when an issue happen in their 
```

2023-01-04 21:54 UTC, pboucherCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +internal logs to investigate. Once our Prefect 2 migration was started, one the first thing we did was create this custom Sentry block type to offer an easy for engineering teams to be notified in th
```suggestion
internal logs to investigate. Once our Prefect 2 migration was started, one the first things we did was create this custom Sentry block type to offer an easy way for engineering teams to be notified in the case of a failure in one of their flow.
```

2023-01-04 21:54 UTC, pboucherCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +As you can imagine, the possibility are infinite in terms of what you can accomplish with custom block types.
```suggestion
As you can imagine, the possibilities are infinite in terms of what you can accomplish with custom block types.
```

2023-01-05 13:45 UTC, amoreauCoveo approved these changes
:gg:

2023-01-05 13:45 UTC, amoreauCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +
You're missing a `<!-- more -->` in your post, which is used to know when to fold the blogpost (otherwise your whole blogpost will be rendered on the front page)
I suggest you add it here

2023-01-05 13:45 UTC, amoreauCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefe
new ones (no apostrophe)

2023-01-05 13:45 UTC, amoreauCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +Sentry is an error monitoring tool that enables developer teams to be notified rapidly when an issue happen in their
when an issue happens (missing s)

2023-01-05 13:45 UTC, amoreauCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +The Sentry block now created in Prefect, we can reuse it in any flow to automatically report on unexpected failures.
First clause is a bit awkward with the second clause. Rephrase to either "With the sentry block now created in Prefect, we can . . ." or "Now that the sentry block has been created in Prefect, we can . . ."
I have a slight preference for the first option

2023-01-05 13:47 UTC, jmprovencher commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +
you're totally right! Nice catch! :D

2023-01-05 14:00 UTC, pboucherCoveo approved these changes

2023-01-05 15:17 UTC, lbourdages approved these changes

2023-01-05 15:17 UTC, lbourdages commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefe
is [Blocks]-> are [Blocks]? It's plural 🤷🏼

2023-01-05 15:33 UTC, lucylu-coveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +internal logs to investigate. Once our Prefect 2 migration was started, one the first things we did was create this custom Sentry block type to offer an easy way for engineering teams to be notified
```suggestion
internal logs to investigate. Once our Prefect 2 migration was started, the first things we did was to create this custom Sentry block type to offer an easy way for engineering teams to be notified in the case of a failure in one of their flow.
```

2023-01-05 15:33 UTC, mpayne-coveo approved these changes
Looks great! I just have a small suggestion for something to maybe elaborate more on, feel free to ignore :smile:

2023-01-05 15:33 UTC, mpayne-coveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +we felt this was not providing us with enough insights regarding what went wrong without having to go through our
It might be worth expanding a bit here on what kind of insights Sentry provides (e.g. culprit/call stack traces, issue tracking/reporting, bug tagging/filtering) that we leverage over other monitoring/alerting tools like Prometheus or Grafana

2023-01-05 15:38 UTC, lucylu-coveo approved these changes

2023-01-05 15:46 UTC, jmprovencher commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefe
not sure about this @amoreauCoveo what do you think ?

2023-01-05 15:46 UTC, jmprovencher commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefe
its the "new concept" that is singular in my mind

2023-01-05 15:47 UTC, jmprovencher commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +internal logs to investigate. Once our Prefect 2 migration was started, one the first things we did was create this custom Sentry block type to offer an easy way for engineering teams to be notified
Not sure about this one. I want to state it was "one of the first things" I did, not THE first thing. Does that makes sense?

2023-01-05 15:47 UTC, jmprovencher commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +we felt this was not providing us with enough insights regarding what went wrong without having to go through our
will do

2023-01-05 16:03 UTC, amoreauCoveo commented on _posts/2023-01-04-creating-custom-sentry-block-prefect-2.md
> +One of the interesting new concepts being offered is [Blocks](https://docs.prefect.io/ui/blocks/?h=block). Blocks allow users to interface with external systems and configurations across flows. Prefe
In this scenario, "Blocks" is a concept. And the subject of the verb is "One"

2023-01-05 16:05 UTC, merged